module.exports = {
  "env": {
    "es6": true,
    "node": true,
  },
  "extends": [
     "eslint:recommended",
     "plugin:@typescript-eslint/recommended",
     "plugin:import/errors",
     "plugin:import/warnings",
     "plugin:no-unsanitized/DOM",
     "plugin:react/recommended",
  ],
  "globals": {
    "console": true,
    "document": true,
    "navigator": true,
    "window": true,
  },
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "comment": true,
    "useJSXTextNode": true,
    "warnOnUnsupportedTypeScriptVersion": false,
    "ecmaFeatures": {
      "jsx": true,
      "modules": true,
    },
    "ecmaVersion": 2018,
    "sourceType": "module",
  },
  "plugins": [
    "import",
    "no-only-tests",
    "no-unsanitized",
    "react",
    "react-hooks",
    "@typescript-eslint",
  ],
  "settings": {
    "import/extensions": [".js", ".jsx"],
    "import/resolver": {"node": {"extensions": [".js", ".jsx", ".tsx", ".ts"]}},
    "react": {
      "version": "detect",
    },
  },
  "rules": {
    "@typescript-eslint/camelcase": "off",
    "@typescript-eslint/class-name-casing": "off",
    "@typescript-eslint/explicit-function-return-type": "off",
    "@typescript-eslint/explicit-member-accessibility": "off",
    "@typescript-eslint/indent": ["error", 2, {"SwitchCase": 1, "VariableDeclarator": 1}],
    "@typescript-eslint/no-explicit-any": "error",
    "@typescript-eslint/no-non-null-assertion": "off",
    "@typescript-eslint/no-this-alias": ["error", { allowDestructuring: true,  allowedNames: ['self', 'that'] }],
    "@typescript-eslint/prefer-interface": "off",
    "arrow-spacing": ["error", { "before": true, "after": true }],
    "block-spacing": "error",
    "brace-style": ["error", "1tbs", { "allowSingleLine": true }],
    "camelcase": "off",
    "comma-dangle": ["error", "always-multiline"],
    "comma-spacing": "error",
    "comma-style": "error",
    "computed-property-spacing": "error",
    "consistent-return": "off",
    "curly": "error",
    "default-case": "off",
    "dot-location": ["error", "property"],
    "dot-notation": "warn",
    "eol-last": "error",
    "eqeqeq": ["error", "always"],
    "func-call-spacing": "error",
    "getter-return": "error",
    "import/newline-after-import": "error",
    "jsx-quotes": "error",
    "key-spacing": "error",
    "keyword-spacing": "error",
    "lines-between-class-members": ["error", "always", { "exceptAfterSingleLine": true }],
    "linebreak-style": "error",
    "new-cap": "off",
    "no-array-constructor": "error",
    "no-caller": "error",
    "no-console": "error",
    "no-else-return": "error",
    "no-empty": "error",
    "no-eq-null": "error",
    "no-eval": "error",
    "no-extra-bind": "error",
    "no-extra-parens": "error",
    "no-implied-eval": "error",
    "no-implicit-globals": "error",
    "no-invalid-this": "off",
    "no-irregular-whitespace": "error",
    "no-lone-blocks": "error",
    "no-multiple-empty-lines": "off",
    "no-multi-spaces": "error",
    "no-new": "error",
    "no-only-tests/no-only-tests": "error",
    "no-param-reassign": "off",
    "no-proto": "error",
    "no-self-compare": "error",
    "no-sequences": "error",
    "no-shadow": "error",
    "no-template-curly-in-string": "error",
    "no-throw-literal": "error",
    "no-trailing-spaces": "error",
    "no-unmodified-loop-condition": "error",
    "no-unneeded-ternary": ["error", { "defaultAssignment": false }],
    "no-unused-expressions": ["error", { "allowShortCircuit": true, "allowTernary": true }],
    "no-use-before-define": ["error", "nofunc"],
    "no-useless-call": "error",
    "no-useless-computed-key": "error",
    "no-useless-concat": "error",
    "no-useless-constructor": "error",
    "no-useless-rename": "error",
    "no-useless-return": "error",
    "no-var": "error",
    "no-whitespace-before-property": "error",
    "object-curly-newline": ["error", { "consistent": true }],
    "object-curly-spacing": ["error", "always"],
    "one-var": "off",
    "operator-linebreak": ["error", "before"],
    "padded-blocks": ["error", "never"],
    "prefer-const": "error",
    "prefer-rest-params": "error",
    "prefer-spread" : "error",
    "prefer-template": "error",
    "quote-props": ["error", "as-needed"],
    "quotes": "off",
    "react-hooks/rules-of-hooks": "error",
    "react-hooks/exhaustive-deps": "warn",
    "react/no-danger": "error",
    "react/no-deprecated": "error",
    "react/no-did-update-set-state": "error",
    "react/no-multi-comp": "off",
    "react/no-string-refs": "warn",
    "react/no-unknown-property": "error",
    "react/no-unsafe": ["error", { "checkAliases": true }],
    "react/no-unused-prop-types": "error",
    "react/prop-types": "off",
    "react/react-in-jsx-scope": "error",
    "react/self-closing-comp": "off",
    "react/sort-comp": "off",
    "react/wrap-multilines": "off",
    "rest-spread-spacing": "error",
    "semi": "error",
    "space-before-blocks": "error",
    "space-before-function-paren": "error",
    "space-in-parens": "error",
    "space-infix-ops": "error",
    "space-unary-ops": "error",
    "spaced-comment": "error",
    "template-curly-spacing": ["error", "never"],
    "unicode-bom": "error",
    "vars-on-top": "off",
    "wrap-iife": ["error", "any"],
    "yoda": "error",
  },
};
