module.exports = {
  "env": {
    "es6": true,
    "node": true,
  },
  "extends": [
     "eslint:recommended",
     "plugin:@typescript-eslint/recommended",
     "plugin:import/errors",
     "plugin:import/warnings",
     "plugin:no-unsanitized/DOM",
     "plugin:react/recommended",
  ],
  "globals": {
    "console": true,
    "document": true,
    "navigator": true,
    "window": true,
  },
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "comment": true,
    "useJSXTextNode": true,
    "warnOnUnsupportedTypeScriptVersion": false,
    "ecmaFeatures": {
      "jsx": true,
      "modules": true,
    },
    "ecmaVersion": 2018,
    "sourceType": "module",
  },
  "plugins": [
    "no-unsanitized",
    "react",
    "react-hooks",
    "@typescript-eslint",
  ],
  "settings": {
    "import/extensions": [".js", ".jsx"],
    "import/resolver": {"node": {"extensions": [".js", ".jsx", ".tsx", ".ts"]}},
    "react": {
      "version": "detect",
    },
  },
  "rules": {
    "@typescript-eslint/indent": ["error", 2, {"SwitchCase": 1, "VariableDeclarator": 1}],
    "@typescript-eslint/prefer-interface": "off",
    "@typescript-eslint/explicit-function-return-type": "off",
    "@typescript-eslint/explicit-member-accessibility": "off",
    "@typescript-eslint/no-var-requires": "off",
    "@typescript-eslint/camelcase": "off",
    "@typescript-eslint/class-name-casing": "off",
    "@typescript-eslint/no-explicit-any": "error",
    "@typescript-eslint/no-non-null-assertion": "off",
    "getter-return": "error",
    "arrow-spacing": ["error", { "before": true, "after": true }],
    "brace-style": ["error", "1tbs", { "allowSingleLine": true }],
    "camelcase": "off",
    "consistent-return": "off",
    "curly": "error",
    "default-case": "off",
    "dot-notation": "warn",
    "eqeqeq": ["error", "always"],
    "indent": ["error", 2, {"SwitchCase": 1, "VariableDeclarator": 1}],
    "jsx-quotes": "error",
    "keyword-spacing": "error",
    "new-cap": "off",
    "no-caller": "error",
    "no-console": "error",
    "no-else-return": "error",
    "no-eq-null": "error",
    "no-eval": "error",
    "no-extra-parens": "error",
    "no-implicit-globals": "error",
    "no-invalid-this": "off",
    "no-irregular-whitespace": "error",
    "no-multiple-empty-lines": "off",
    "no-param-reassign": "off",
    "no-shadow": "error",
    "no-trailing-spaces": "error",
    "no-use-before-define": "error",
    "no-useless-concat": "error",
    "no-var": "error",
    "object-curly-spacing": ["error", "always"],
    "one-var": "off",
    "padded-blocks": ["error", "never"],
    "prefer-const": "error",
    "prefer-template": "warn",
    "quotes": "off",
    "react-hooks/rules-of-hooks": "error",
    "react/no-multi-comp": "off",
    "react/no-string-refs": "warn",
    "react/prop-types": "off",
    "react/self-closing-comp": "off",
    "react/sort-comp": "off",
    "react/wrap-multilines": "off",
    "semi": ["error", "always"],
    "space-before-blocks": ["error", "always"],
    "space-before-function-paren": ["error", "always"],
    "spaced-comment": "error",
    "vars-on-top": "off",
  },
};
