module.exports = {
  "extends": ["./index"],
  "plugins": [
    "import",
    "react-hooks",
    "react",
    "@typescript-eslint"
  ],
  "rules": {
    "@typescript-eslint/no-parameter-properties": "error",
    "comma-dangle": ["error", { "arrays": "always-multiline", "objects": "always-multiline", "imports": "always-multiline", "exports": "always-multiline" }],
    "comma-spacing": "error",
    "comma-style": "error",
    "computed-property-spacing": "error",
    "dot-location": ["error", "property"],
    "eol-last": "error",
    "func-call-spacing": "error",
    "import/order": ["error", {"groups": ["builtin", "external", ["internal", "parent", "sibling"], "index"]}],
    "import/newline-after-import": "error",
    "key-spacing": "error",
    "lines-between-class-members": ["error", "always", { "exceptAfterSingleLine": true }],
    "linebreak-style": "error",
    "max-len": ["error", { "code": 120, "ignoreUrls": true, "ignoreStrings": true, "ignoreTemplateLiterals": true }],
    "max-params": ["error", 5],
    "no-array-constructor": "error",
    "no-empty": "error",
    "no-extra-bind": "error",
    "no-implied-eval": "error",
    "no-lone-blocks": "error",
    "no-mixed-operators": "error",
    "no-multi-spaces": "error",
    "no-multiple-empty-lines": "error",
    "no-new": "error",
    "no-param-reassign": ["error", { "props": false }],
    "no-proto": "error",
    "no-self-compare": "error",
    "no-sequences": "error",
    "no-template-curly-in-string": "error",
    "no-throw-literal": "error",
    "no-unmodified-loop-condition": "error",
    "no-unneeded-ternary": ["error", { "defaultAssignment": false }],
    "no-unused-expressions": ["error", { "allowShortCircuit": true, "allowTernary": true }],
    "no-useless-call": "error",
    "no-useless-computed-key": "error",
    "no-useless-constructor": "error",
    "no-useless-rename": "error",
    "no-useless-return": "error",
    "no-whitespace-before-property": "error",
    "object-curly-newline": ["error", { "consistent": true }],
    "operator-linebreak": ["error", "before"],
    "quote-props": ["error", "as-needed"],
    "quotes": ["error", "single"],
    "react-hooks/exhaustive-deps": "warn",
    "react/no-did-update-set-state": "error",
    "react/no-unknown-property": "error",
    "react/no-unused-prop-types": "error",
    "react/react-in-jsx-scope": "error",
    "react/self-closing-comp": "error",
    "rest-spread-spacing": "error",
    "space-in-parens": "error",
    "space-infix-ops": "error",
    "space-unary-ops": "error",
    "unicode-bom": "error",
    "wrap-iife": ["error", "any"],
    "yoda": "error"
  }
};
